[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ispawn"
version = "0.1.0"
authors = [
  { name="jfouret" },
]
description = "A tool to spawn docker containers holding multiple services with a single command"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pyyaml>=6.0",
    "jinja2>=3.0.0",
    "docker>=6.0.0",
    "command_runner>=1.3.0"
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-mock>=3.10.0",
    "pytest-docker>=2.0.0"
]
dev = [
    "black>=23.0.0",
    "isort>=5.12.0",
    "mypy>=1.0.0",
    "pylint>=2.17.0"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=ispawn --cov-report=term-missing"
markers = [
    "e2e: marks tests as end-to-end tests",
    "integration: marks tests as integration tests"
]

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[project.scripts]
ispawn = "ispawn.main:main"
