FROM {{image}}
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y wget sudo {{ 'python3-pip' if 'jupyter' in services else '' }}

# Install RStudio Server if requested
{% if 'rstudio' == service %}
RUN if [ -z "$(which rstudio-server)" ]; then \
        apt update && apt install -y gdebi-core libssl-dev libcurl4-gnutls-dev libxml2-dev; \
        . /etc/os-release; \
        wget https://download2.rstudio.org/server/${VERSION_CODENAME}/amd64/rstudio-server-2023.12.1-402-amd64.deb; \
        gdebi -n rstudio-server-2023.12.1-402-amd64.deb; \
    else \
        echo "RStudio Server is already installed."; \
    fi

# Configure RStudio Server
RUN echo "" >> $(Rscript -e 'cat(R.home())')/etc/Renviron.site \
  && cat /etc/environment >> $(Rscript -e 'cat(R.home())')/etc/Renviron.site
{% endif %}

# Install Jupyter Notebook if requested
{% if 'jupyter' == service %}
RUN pip3 install notebook
{% endif %}

# Create the entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

{% if 'rstudio' == service %}
EXPOSE 8787
{% endif %}
{% if 'jupyter' == service %}
EXPOSE 8888
{% endif %}

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD []