FROM {{ base }}

# Install basic system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    adduser \
    ca-certificates \
    tar \
    bzip2 \
    wget \
    sudo \
    passwd \
    locales \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8

{% if has_env_in_context %}
# Copy and process environment file
COPY environment /tmp/environment
RUN cat /tmp/environment >> /etc/environment && \
    rm /tmp/environment
{% endif %}

{{ service_chunks | safe }}

{{ dockerfile_chunk | safe }}

# Copy entrypoint script
COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

# COPY service entrypoints
{% for service in services %}
COPY ispawn-entrypoint-{{service}}.sh /usr/local/bin/ispawn-entrypoint-{{service}}.sh
{% endfor %}

RUN for i in $(seq -w 0 100) ; do (userdel $(id -nu 1$i) || true) ; done

# Set entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
