name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write  # Need write permission to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (main branch)
        uses: actions/checkout@v4
        with:
          path: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: main
        run: |
          pip install poetry==2.1.2
          poetry install --with dev

      - name: Determine version
        working-directory: main
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            echo "IS_TAG=true" >> $GITHUB_ENV
          else
            echo "VERSION=main" >> $GITHUB_ENV
            echo "IS_TAG=false" >> $GITHUB_ENV
          fi

      - name: Verify version match (for tags)
        working-directory: main
        run: |
          python .github/scripts/update_docs_gh_version.py --version $VERSION --project-root .

      - name: Build documentation
        working-directory: main
        run: |
          cd docs
          poetry run make html

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          
      - name: Update documentation
        run: |
          # Create version directory if it doesn't exist
          mkdir -p gh-pages/$VERSION
          
          # Copy built documentation to version directory
          cp -r main/docs/build/html/* gh-pages/$VERSION/
          
          # Update switcher.json
          python main/.github/scripts/update_docs_gh_version.py --version $VERSION --site-dir gh-pages

      - name: Configure Git
        run: |
          cd gh-pages
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          cd gh-pages
          git add .
          git commit -m "Update documentation for $VERSION" || echo "No changes to commit"
          git push
